#!/bin/bash
# MarketOS Ledger - Quick Start Guide

echo "========================================"
echo "MarketOS Ledger - Quick Start"
echo "========================================"
echo ""
echo "✅ Project setup complete!"
echo ""
echo "📦 Installed Packages:"
echo "   - React 18"
echo "   - Vite 5"
echo "   - Electron 27"
echo "   - Tailwind CSS"
echo "   - SQLite (better-sqlite3)"
echo "   - React Router"
echo "   - Day.js"
echo ""
echo "🚀 To run the application:"
echo ""
echo "   npm run electron-dev"
echo ""
echo "   This will start:"
echo "   - Vite dev server (http://localhost:5173)"
echo "   - Electron window"
echo ""
echo "💡 Alternatively, run in separate terminals:"
echo "   Terminal 1: npm run dev"
echo "   Terminal 2: npm run electron"
echo ""
echo "📦 To build for production:"
echo "   npm run build"
echo "   npm run electron-build"
echo ""
echo "========================================"
echo "Happy coding! 🎉"
echo "========================================"
